server.port: 8090

spring:
    datasource:
        url: jdbc:sqlite:E:\skill up\DOING\trader\code\counter.db
        driver-class-name: org.sqlite.JDBC
    redis:
        host: 192.168.140.157
        port: 6379
        timeout: 6000ms

mybatis:
    mapper-locations: classpath:mapper/*.xml
mybatis-plus:
    configuration:
        jdbc-type-for-null: 'null'

# 缓存过期时间
cacheexpire:
    captcha: 100
    account: 3600
    order: 36000

# 机器位置：机房id，机柜id
counter:
    dataCenterId: 0
    workerId: 0
